//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2013/8/2 17:13:38
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using WcfStatistics.Model;

namespace WcfStatistics.Dao.Int {
	
    /// <summary><c>IBatchDao</c> is the DAO interface for <see cref="WcfStatistics.Model.Batch"/>.</summary>
    public partial interface IBatchDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="Batch"/> instance by the primary key value.</summary>
		Batch Find(Int32 iD);

		/// <summary>Finds all Batch instances.</summary>
		IList<Batch> FindAll();
		
		/// <summary>Finds all Batch instances without Lob columns loaded.</summary>
		IList<Batch> QuickFindAll();
		
		/// <summary>Finds Batch instances by CreateTime value.</summary>
		IList<Batch> FindByCreateTime(DateTime? createTime);
		
		/// <summary>Inserts a new Batch instance into underlying database table.</summary>
		int Insert(Batch obj);
		
		/// <summary>Update the underlying database record of a Batch instance.</summary>
		void Update(Batch obj);
		
		/// <summary>Delete the underlying database record of a Batch instance.</summary>
		void Delete(Batch obj);
		
        /// <summary>Deletes <see cref="Batch"/> instances by <see cref="Batch.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime? createTime);
		
		/// <summary>Reload the underlying database record of a Batch instance.</summary>
		void Reload(Batch obj);
		
	}

}
