//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2013/8/2 17:13:38
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using WcfStatistics.Model;

namespace WcfStatistics.Dao.Int {
	
    /// <summary><c>IWcfServerDao</c> is the DAO interface for <see cref="WcfStatistics.Model.WcfServer"/>.</summary>
    public partial interface IWcfServerDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="WcfServer"/> instance by the primary key value.</summary>
		WcfServer Find(Int32 iD);

		/// <summary>Finds all WcfServer instances.</summary>
		IList<WcfServer> FindAll();
		
		/// <summary>Finds all WcfServer instances without Lob columns loaded.</summary>
		IList<WcfServer> QuickFindAll();
		
		/// <summary>Finds WcfServer instances by IP value.</summary>
		IList<WcfServer> FindByIP(String iP);
		
		/// <summary>Finds WcfServer instances by Point value.</summary>
		IList<WcfServer> FindByPoint(Int32? point);
		
		/// <summary>Finds WcfServer instances by Remark value.</summary>
		IList<WcfServer> FindByRemark(String remark);
		
		/// <summary>Finds WcfServer instances by CreateTime value.</summary>
		IList<WcfServer> FindByCreateTime(DateTime? createTime);
		
		/// <summary>Inserts a new WcfServer instance into underlying database table.</summary>
		void Insert(WcfServer obj);
		
		/// <summary>Update the underlying database record of a WcfServer instance.</summary>
		void Update(WcfServer obj);
		
		/// <summary>Delete the underlying database record of a WcfServer instance.</summary>
		void Delete(WcfServer obj);
		
        /// <summary>Deletes <see cref="WcfServer"/> instances by <see cref="WcfServer.IP"/>.</summary>
		int DeleteByIP(String iP);
		
        /// <summary>Deletes <see cref="WcfServer"/> instances by <see cref="WcfServer.Point"/>.</summary>
		int DeleteByPoint(Int32? point);
		
        /// <summary>Deletes <see cref="WcfServer"/> instances by <see cref="WcfServer.Remark"/>.</summary>
		int DeleteByRemark(String remark);
		
        /// <summary>Deletes <see cref="WcfServer"/> instances by <see cref="WcfServer.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime? createTime);
		
		/// <summary>Reload the underlying database record of a WcfServer instance.</summary>
		void Reload(WcfServer obj);
		
	}

}
