//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2013/8/2 17:13:38
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace WcfStatistics.Model {
	
    /// <summary><c>Batch</c> Business Object.</summary>
    [Serializable]
    public partial class Batch {
        
        #region ID

        private Int32 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int32 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime? m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime? CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		

	}
	
}
