//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2013/8/2 17:13:38
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace WcfStatistics.Model {
	
    /// <summary><c>ClientConnInfo</c> Business Object.</summary>
    [Serializable]
    public partial class ClientConnInfo {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region ServerID

        private Int32? m_serverID;
		
		/// <summary>Gets or sets ServerID</summary>
        public Int32? ServerID {
        	get { return m_serverID; }
        	set { m_serverID = value;}        
        }
		
	    #endregion
		
        #region BatchID

        private Int32? m_batchID;
		
		/// <summary>Gets or sets BatchID</summary>
        public Int32? BatchID {
        	get { return m_batchID; }
        	set { m_batchID = value;}        
        }
		
	    #endregion
		
        #region IP

        private String m_iP;
		
		/// <summary>Gets or sets IP</summary>
        public String IP {
        	get { return m_iP; }
        	set { m_iP = value;}        
        }
		
	    #endregion
		
        #region Adress

        private String m_adress;
		
		/// <summary>Gets or sets Adress</summary>
        public String Adress {
        	get { return m_adress; }
        	set { m_adress = value;}        
        }
		
	    #endregion
		
        #region LinkNums

        private Int32? m_linkNums;
		
		/// <summary>Gets or sets LinkNums</summary>
        public Int32? LinkNums {
        	get { return m_linkNums; }
        	set { m_linkNums = value;}        
        }
		
	    #endregion

        private string m_AppName;

        public string AppName
        {
            get { return m_AppName; }
            set { m_AppName = value; }
        }
	}
	
}
