//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2013/8/2 17:13:38
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace WcfStatistics.Model {
	
    /// <summary><c>WcfServerPerformance</c> Business Object.</summary>
    [Serializable]
    public partial class WcfServerPerformance {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region ServerID

        private Int32? m_serverID;
		
		/// <summary>Gets or sets ServerID</summary>
        public Int32? ServerID {
        	get { return m_serverID; }
        	set { m_serverID = value;}        
        }
		
	    #endregion
		
        #region BatchID

        private Int32? m_batchID;
		
		/// <summary>Gets or sets BatchID</summary>
        public Int32? BatchID {
        	get { return m_batchID; }
        	set { m_batchID = value;}        
        }
		
	    #endregion
		
        #region CurrentConnNums

        private Int32? m_currentConnNums;
		
		/// <summary>Gets or sets CurrentConnNums</summary>
        public Int32? CurrentConnNums {
        	get { return m_currentConnNums; }
        	set { m_currentConnNums = value;}        
        }
		
	    #endregion
		
        #region ProcessId

        private Int32? m_processId;
		
		/// <summary>Gets or sets ProcessId</summary>
        public Int32? ProcessId {
        	get { return m_processId; }
        	set { m_processId = value;}        
        }
		
	    #endregion
		
        #region Cpu

        private Decimal? m_cpu;
		
		/// <summary>Gets or sets Cpu</summary>
        public Decimal? Cpu {
        	get { return m_cpu; }
        	set { m_cpu = value;}        
        }
		
	    #endregion
		
        #region Mem

        private Decimal? m_mem;
		
		/// <summary>Gets or sets Mem</summary>
        public Decimal? Mem {
        	get { return m_mem; }
        	set { m_mem = value;}        
        }
		
	    #endregion
		
        #region AllMem

        private Decimal? m_allMem;
		
		/// <summary>Gets or sets AllMem</summary>
        public Decimal? AllMem {
        	get { return m_allMem; }
        	set { m_allMem = value;}        
        }
		
	    #endregion
		
        #region ThreadCount

        private Int32? m_threadCount;
		
		/// <summary>Gets or sets ThreadCount</summary>
        public Int32? ThreadCount {
        	get { return m_threadCount; }
        	set { m_threadCount = value;}        
        }
		
	    #endregion
		

	}
	
}
